echo "Test 1";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -f /Users//konstantinvoronin/ACSHomework2/tests/test1.txt /Users/konstantinvoronin/ACSHomework2/tests/test1_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/test1_output2.txt;
echo "Test 2";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -f /Users/konstantinvoronin/ACSHomework2/tests/test2.txt /Users/konstantinvoronin/ACSHomework2/tests/test2_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/test2_output2.txt;
echo "Test 3";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -f /Users/konstantinvoronin/ACSHomework2/tests/test3.txt /Users/konstantinvoronin/ACSHomework2/tests/test3_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/test3_output2.txt;
echo "Test 4";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -f /Users/konstantinvoronin/ACSHomework2/tests/test4.txt /Users/konstantinvoronin/ACSHomework2/tests/test4_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/test4_output2.txt;
echo "Test 5";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -f /Users/konstantinvoronin/ACSHomework2/tests/test5.txt /Users/konstantinvoronin/ACSHomework2/tests/test5_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/test5_output2.txt;
echo "Random Test 1(5000)";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -n 5000 /Users/konstantinvoronin/ACSHomework2/tests/randomtest1_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/randomtest1_output2.txt;
echo "Random Test 2(333)";
time /Users/konstantinvoronin/ACSHomework2/bin/ACSHomework2 -n 333 /Users/konstantinvoronin/ACSHomework2/tests/randomtest2_output1.txt /Users/konstantinvoronin/ACSHomework2/tests/randomtest2_output2.txt;
